name: Test zip package creation

on:
  workflow_dispatch:

jobs:
  release_package:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the june-cheque-app repo
      uses: actions/checkout@v2
      with:
        path: june-cheque-app

    - name: install needed stuff
      run: |
           sudo apt-get install git wget curl unzip build-essential software-properties-common ruby ruby-dev ruby-ffi gcc make
           wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
           export NVM_DIR="$HOME/.nvm"
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
           [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
           nvm install 16
           npm install -g yarn gulp cordova @ionic/cli@6.20.9 web-ext

    - name: build everything
      run: |
           cd june-cheque-app
           yarn
           gulp config

    - name: create the package
      run: |
        cd june-cheque-app
        gulp webBuild --release

    - name: install needed test packages
      run: |
        sudo apt-get install httest

    - name: release the package
      run: |
        cd june-cheque-app
        VERSION=v1.0.2 RELEASE_BRANCH=$GITHUB_REF_NAME httest pkg/release.htt
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

    - name: encode httest log
      if: ${{ failure() }}
      run: |
        cat june-cheque-app/httest.log | openssl enc -aes256 -pbkdf2 -k $CHECKFILE_PASSKEY > june-cheque-app/httest.log.enc
      env:
        CHECKFILE_PASSKEY: ${{ secrets.CHECKFILE_PASSKEY }}

    - name: archive httest log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: httest-log
        path: june-cheque-app/httest.log.enc
